Câu 99: Nhập vào tọa độ 2 điểm A(xA, yA) và B(xB, yB). Tính khoảng cách AB.

In [8]:
from math import sqrt
xA=float(input("Nhập vào xA: "))
yA=float(input("Nhập vào yA: "))
xB=float(input("Nhập vào xB: "))
yB=float(input("Nhập vào yB: "))
distance=sqrt(pow((xA-xB),2)+pow((yA-yB),2))
print("Khoảng cách là:",distance)

Nhập vào xA: 2
Nhập vào yA: 4
Nhập vào xB: 5
Nhập vào yB: 3
Khoảng cách là: 3.1622776601683795


Câu 100: Viết chương trình nhập vào tọa độ (xC, yC) là tâm của một đường tròn, và R
là bán kính của đường tròn đó. Nhập vào tọa độ (xM, yM) của điểm M. Xác định điểm
M nằm trong, nằm trên hay nằm ngoài đường tròn.

In [11]:
xC=float(input("Nhập vào xC: "))
yC=float(input("Nhập vào yC: "))
r=float(input("Nhập vào bán kính r: "))
xM=float(input("Nhập vào xM: "))
yM=float(input("Nhập vào yM: "))
distance=sqrt(pow((xC-xM),2)+pow((yC-yM),2))
if distance>r:
    print("M nằm ngoài đường tròn bán kính %.2f"%r)
elif distance==r:
    print("M nằm trên đường tròn bán kính %2.f"%r)
else:
    print("M nằm trong đường tròn bán kính %2.f"%r)

Nhập vào xC: 3
Nhập vào yC: 3
Nhập vào bán kính r: 3.5
Nhập vào xM: 9
Nhập vào yM: 10
M nằm ngoài đường tròn bán kính 3.50


Câu 101: Viết chương trình giải phương trình bậc 1: ax + b = 0 (a, b nhập từ bàn phím).

In [15]:
print("Giải phương trình bậc 1 ax+b = 0")
a=float(input("Nhập vào giá trị a: "))
b=float(input("Nhập vào giá trị b: "))
if a==0:
    print("Phương trình vô số nghiệm")
else:
    x=-b/a
    print("Phương trình ax+b=0 có nghiệm là"+str(x))

Giải phương trình bậc 1 ax+b = 0
Nhập vào giá trị a: 34
Nhập vào giá trị b: 43
Phương trình ax+b=0 có nghiệm là-1.2647058823529411


Câu 102: Viết chương trình giải phương trình bậc 2: ax2 + bx + c = 0 (a, b, c nhập từ
bàn phím). Xét tất cả các trường hợp có thể.

In [22]:
from math import sqrt
print("Giải phương trình bậc 2 ax^2 + bx+ c = 0 ")
a=float(input("Nhập vào giá trị a: "))
b=float(input("Nhập vào giá trị b: "))
c=float(input("Nhập vào giá trị c: "))
delta=pow(b,2)-4*a*c
if delta<0:
    print("Phương trình vô nghiệm")
elif delta==0:
    print("Phương trình có nghiệm kép:",-b/(2*a))
else:
    x1=(-b+sqrt(delta))/2*a
    x2=(-b-sqrt(delta))/2*a
    print("Nghiệm x1 là",x1)
    print("Nghiệm x2 là",x2)

Giải phương trình bậc 2 ax^2 + bx+ c = 0 
Nhập vào giá trị a: 2
Nhập vào giá trị b: 9
Nhập vào giá trị c: 4
Nghiệm x1 là -2.0
Nghiệm x2 là -16.0


Câu 103: Viết chương trình giải hệ phương trình 2 ẩn:

In [1]:
print("Giải hệ phương trình 2 ẩn:\n a1x^2 + b1y=c1\n a2^2 + b2y=c2")
a1=float(input("Nhập a1: "))
b1=float(input("Nhập b1: "))
c1=float(input("Nhập c1: "))
a2=float(input("Nhập a2: "))
b2=float(input("Nhập b2: "))
c2=float(input("Nhập c2: "))
detD=a1*b2-a2*b1
detDx=c1*b2-c2*b1
detDy=a1*c2-a2*c1
if detD!=0:
    x=detDx/detD
    y=detDy/detD
    print("Nghiệm của hệ phương trình x: "+str(x)+" và y: "+str(y))
elif detD==0 and detDx!=0 or detDy!=0:
    print("Hệ phương trình vô nghiệm")
else:
    print("Hệ phương trình vô số nghiệm")

Giải hệ phương trình 2 ẩn:
 a1x^2 + b1y=c1
 a2^2 + b2y=c2
Nhập a1: 2
Nhập b1: 4
Nhập c1: 5
Nhập a2: 3
Nhập b2: 8
Nhập c2: 4
Nghiệm của hệ phương trình x: 6.0 và y: -1.75


Câu 104: Viết chương trình liệt kê, đếm và tính tổng các ước số của số nguyên dương
n (n nhập từ bàn phím).

In [6]:
n=int(input("Nhập n: "))
i=1
s=0
while(i<=n):
    if n%i==0:
        s=s+i
    i+=1
print("Tổng ước là",s)

Nhập n: 13
Tổng ước là 14


Câu 105: Viết chương trình tìm các số hoàn hảo (perfect number) nhỏ hơn một số
nguyên dương n cho trước. Biết số hoàn hảo là số nguyên dương, bằng tổng các ước
số thực sự của nó(ví dụ: 28 = 14 + 7 + 4 + 2 + 1).

In [13]:
n=int(input("Nhập n: "))
i=1
s=0
while(i<n):
    if n%i==0:
        s=s+i
    i+=1
if s==n:
    print("n là số hoàn hảo")
else:
    print("n không là số hoàn hảo")

Nhập n: 20
n không là số hoàn hảo


Câu 106: Nhập vào một số tự nhiên n (n khai báo kiểu unsigned long)
    
a. Số tự nhiên n có bao nhiêu chữ số.

b. Hãy tìm chữ số cuối cùng của n.

c. Hãy tìm chữ số đầu tiên của n.

d. Tính tổng các chữ số của n.

e. Hãy tìm số đảo ngược của n.

In [44]:
n=input("Nhập n: ")
print("Số n có "+ str(len(n))+" chữ số")
l=list(n)
l_new=[int(i) for i in l]
l_new
print("Chữ số cuối cùng của n là "+str(l_new[-1]))
print("Chữ số đầu tiên của n là "+str(l_new[0]))
s=0
for l in l_new:
    s=s+l
print("Tổng các chữ số của n là "+str(s))
l_reverse=[0 for i in l_new]
for i in range(len(l_new)):
    l_dao[i]=l_new[len(l_new)-1-i]
print("Số đảo ngược của n là: ")
for i in l_dao:
    print(i,end='')
    

Nhập n: 1938
Số n có 4 chữ số
Chữ số cuối cùng của n là 8
Chữ số đầu tiên của n là 1
Tổng các chữ số của n là 21
Số đảo ngược của n là: 
8391

Câu 107: Nhập vào hai số nguyên dương a, b. Tính ước số chung lớn nhất và bội số
chung nhỏ nhất của a, b.

In [13]:
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
i=0
while(i<=a*b):
    if i%a==0 and i%b==0 and i!=0:
        print("Bội chung nhỏ nhất của a và b là:",i)
        break
    else:
        i+=1
while a!=b:
    if a>b:
        a=a-b
    else:
        b=b-a
print("Ước chung lớn nhất của a và b là",a)

Nhập a: 5
Nhập b: 10
Bội chung nhỏ nhất của a và b là: 10
Ước chung lớn nhất của a và b là 5


Câu 108: Nhập vào tử số, mẫu số (đều khác 0) của một phân số.

In [2]:
tuso=int(input("Nhập tử số: "))
mauso=int(input("Nhập mẫu số: "))
t=tuso
m=mauso
while tuso!=mauso:
    if tuso>mauso:
        tuso=tuso-mauso
    else:
        mauso=mauso-tuso
tuso_new=int(t/tuso)
mauso_new=int(m/tuso)
print("Phân số rút gọn: "+str(tuso_new)+'/'+str(mauso_new))

Nhập tử số: 12
Nhập mẫu số: 15
Phân số rút gọn: 4/5


Câu 109: Nhập vào một số nguyên dương n, phân tích n thành các thừa số nguyên tố.

In [11]:
n=int(input("Nhập n: "))
for i in range(2,n+1):
    dem=0
    while(n%i==0):
        dem+=1
        n/=i
    if dem:
        if dem>1:
            print(i,"^",dem,end="")
        else:
            print(i,end="")
        if n>i:
            print("*",end="")

Nhập n: 12
2 ^ 2*3

Câu 110: Viết chương trình nhập lãi xuất năm r (%), tiền vốn p và thời hạn gởi tiền n
(năm). In ra vốn tích lũy a của từng năm.
Chương trình có kiểm tra nhập thiếu hoặc nhập lỗi.

In [18]:
r=float(input("Nhập lãi suất(%): "))
p=float(input("Nhập tiền vốn(tr): "))
n=float(input("Thời gian gửi(năm): "))
if r and p and n:
    m=p*pow(1+r,n)
    print("Tiền lãi sau "+str(n)+" năm là "+str(m-p))
else:
    print("Bạn nhập thiếu giá trị")

Nhập lãi suất(%): 0.015
Nhập tiền vốn(tr): 3
Thời gian gửi(năm): 4
Tiền lãi sau 4.0 năm là 0.18409065187499873


Câu 111:Viết chương trình C, xuất ra các dòng có định dạng sau

Lưu ý: có xuống dòng ở dòng cuối cùng.


Programming...

..1

...2

....3

In [19]:
print("Programming...");print("..1");print("...2");print("....3")

Programming...
..1
...2
....3


Câu 112: Viết chương trình chuyển đổi độ Fahrenheit (F) sang độ Celsius (C) theo công thức sau:

C = (F - 32) / 1.8

Kết quả được làm tròn còn 2 số thập phân.

input: Độ Fahrenheit.

Kết quả xuất ra màn hình theo định dạng với giá trị input = 59 là:

59F = 15.00C

Lưu ý: không có dấu xuống dòng.

In [28]:
F=int(input("Nhập vào độ F: "))
C=(F-32)/1.8
print("%dF = %.2fC"%(F,C))

Nhập vào độ F: 59
59F = 15.00C


Câu 113: Cho chương trình sau:
```C
#include <stdio.h>
int main(void)
{
  int a = 25, b = 5, c = 10, d = 7;
  //TODO
  return 0;
}
```
Hãy hoàn thiện đoạn chương trình trên (bằng cách thay thế đoạn //TODO 

Tính toán và xuất ra các dòng có định dạng sau

Lưu ý: có xuống dòng ở dòng cuối cùng.

a % b = ???

a % c = ???

a % d = ???

a / d * d + a % d = ???



Lưu ý:  các kết quả trong ??? cần được tính toán bởi cú pháp chương trình với các biến a, b, c, d.

In [35]:
a = 25;b = 5; c = 10;d = 7
print("a%b = "+str(a%b))
print("a%%c= %d"%(a%c))
print("a%d= ",a%d)
print("a/d*d + a%d= "+str(a/d*d+a%d))

a%b = 0
a%c= 5
a%d=  4
a/d*d + a%d= 29.0


Câu 114: Viết chương trình lần lượt xuất ra số byte của các kiểu dữ liệu sau theo từng hàng tương ứng:
- unsigned int
- int
- float
- double
- char

Theo định dang: "Storage size for <kiểu dữ liệu> : <value> byte". Biết <kiểu dữ liệu> là 5 kiểu trên, <value> là
một số nguyên dương cho biết kích thước của kiểu dữ liệu. Không có xuống hàng dòng cuối cùng.

In [47]:
import sys
sys.getsizeof(int())
sys.getsizeof(float())
sys.getsizeof(bool())
sys.getsizeof(str())
sys.getsizeof(list())

36

Câu 115: Viết chương trình in ra mã ASCII của một ký tự:
        
Input: ký tự
    
Output: 'ký tự' = code ASCII

Example:
    
Input: A
    
Output: 'A' = 65

In [56]:
k=input("Nhập 1 ký tự bất kỳ: ")
print(k+' = '+str(ord(k)))

Nhập 1 ký tự bất kỳ: A
A = 65


Câu 116: Hãy viết chương trình thể hiện tiêu đề cột trước tiên và sau đó quyết định độ rộng cột như sau:

- Canh lề phải dòng thứ 2
- Canh lề trái dòng cuối

Ví dụ dưới đây trình bày chi tiết cách tạo:

Column1 Column2 Column3

        100        1221       9348
        
23            211         214

In [61]:
print("Column1 Column2 Column3")
print("\t100\t1221\t9348")
print("23 211 214")

Column1 Column2 Column3
	100	1221	9348
23 211 214


Câu 117: Viết chương trình lần lược in tất cả thực hiện các phép toán của 2 số nguyên 21 và 10. Thứ tự các xử lý như sau:

1: +; 2: -; 3: *, 4: /; 5: %; 6: ++ giá tri 21; 7: -- giá tri 21

Lưu ý có xuống dòng ở hàng cuối cùng.

Output:

Operation <k> - Value of c is <???>

Thí dụ: Operation 1 - Value of c is 31

In [62]:
a=21;b=10
print("Phép cộng",a+b)
print("Phép trừ",a-b)
print("Phép nhân",a*b)
print("Phép chia",a/b)
print("Phép lấy dư",a%b)

Phép cộng 31
Phép trừ 11
Phép nhân 210
Phép chia 2.1
Phép lấy dư 1


Câu 118: Viết và chạy một chương trình thực hiện các bước sau:
- Gán giá trị cho bán kính r = 100m.

- Tính chu vi theo công thức: C = 2πr (Pi = 3.14159).

- Tính diện tích đường tròn

- Hiển thị chu vi, diện tích với 7 số lẻ.

In [64]:
r=100
pi=3.14159
print("Chu vi %.7f"%(2*pi*r))
print("Diện tích %.7f"%(pi*r**2))

Chu vi 628.3180000
Diện tích 31415.9000000


Câu 119: Cho một khoản tiền gửi ban đầu, ký hiệu là P, vào một ngân hàng trả lãi hàng năm, số tiền tại thời điểm N năm sau được cho bởi công thức:

Số tiền = P * (1 + R) N

trong đó R là lãi suất dưới dạng số thập phân (Thí dụ: 6,5% là 0,065).
Sử dụng công thức này, hãy thiết kế, viết và chạy một chương trình xác định số tiền sẽ có trong 4 năm
nếu 10.000 đô la được gửi vào ngân hàng trả lãi suất 7% hàng năm.

In [67]:
p=10000
r=0.07
n=4
sotien=p*((1+r)**n)
print("Số tiền lãi và lời là",sotien)

Số tiền lãi và lời là 13107.960100000002


Câu 120: Viết chương trình chuyển đổi số ngày thành năm, tuần và ngày.

Ví dụ: 1532 ngày = 4 năm + 10 tuần + 2 ngày.

Học sinh cần gán giá trị cho số ngày và hiển thị kết quả như trên với 10002. Giả sử một năm có 365 ngày.

In [75]:
def covert(n):
    y=n//365
    m=(n%365)//7
    d=(n%365)%7
    print(n," = ",y,"năm",m,"tuần",d,"ngày")
covert(1532)

1532  =  4 năm 10 tuần 2 ngày


Câu 121: Thực hiện chuyển đổi đơn giản giữa các kiểu dữ liệu số:

Xuất ra kết quả cho trường hợp các biến f1 = 123.125, i2 = -150:
    
123.125000 assigned to an int produces 123

-150 assigned to a float produces -150.000000

-150 divided by 100 produces -1.000000

-150 divided by 100.0 produces -1.500000

(float) -150 divided by 100 produces -1.500000


Cho biến các biến sau:

- f1 = -856.339;

- i2 = -250;

In [89]:
f1=123.125;i2=-150
print("%.6f assigned to an int produces %d"%(f1,f1))
print("%d assigned to an int produces %.7f"%(i2,i2))
print("%d  divided by 100 produces %.7f"%(i2,i2//100+1))
print("%d  divided by 100.0 produces %.7f"%(i2,i2/100))

123.125000 assigned to an int produces 123
-150 assigned to an int produces -150.0000000
-150  divided by 100 produces -1.0000000
-150  divided by 100.0 produces -1.5000000


Câu 122: Viết chương trình tính đa thức sau, làm tròn 3 số thập phân:
        
4X^3 -5X^2 + 7

Biết X =  2.55


Input: một số thực
    
Output: giá trị của đa thức
    
Example:
    
Input: 2.25
    
Output: 27.250

In [91]:
x=2.25
print(4*x**3-5*x**2+7)

27.25


Câu 123: Viết chương trình in các chuỗi "Hello World!" sau theo định dạng, với |_| thể hiện khoảng trắng.
_|_|_|Hello World!_|_|_|_|end!

In [93]:
print(" ",end='');print("Hello World!",end='');print(" ",end='');print("end!",end='')

 Hello World! end!

Câu 124: Viết chương trình đánh giá biểu thức sau và hiển thị kết quả (nhớ sử dụng định dạng hàm mũ để hiển thị kết quả):

(3.31 x 10^-8 x 2.01 x 10^-7) / (7.16 x 10^-6 + 2.01 x 10^-8)

In [94]:
tuso=3.31*10**(-8)*2.01*10**(-7)
mauso=7.16*10**(-6)+2.01+10**(-8)
phanso=tuso/mauso
print(phanso)

3.309988192728685e-15


Câu 125: Hãy định nghĩa các biến A = 70.0, B = 3 sau và lần lượt in kết quả các toán tử sau
- Example += operator A = ???
- Example -= operator B = ???
- Example *= operator A = ???
- Example /= operator B = ???
- Example %= operator A = ???

In [95]:
a=70;b=3
print("+= operator A =",a+b)
print("-= operator A =",a-b)
print("*= operator A =",a*b)
print("/= operator A =",a/b)
print("%= operator A =",a%b)

+= operator A = 73
-= operator A = 67
*= operator A = 210
/= operator A = 23.333333333333332
%= operator A = 1


Câu 126: Viết chương trình hỗ trợ và xuất ra kết quả các phép tính toán kết hợp giữa hai số nguyên a và b.

Các option dùng để trả về kết quả:

1 : (a + b)

2 : (a - b)

3 : (a * b)

4 : (a / b)

5 : a^2 + b^2

Trong trường hợp phép chia (option 4), nếu b bằng 0 thì xuất ra theo định dạng "Do not divide <number_a> by zero!".
Ví dụ: a = 6, b = 0 thì xuất ra: "Do not divide 6 by zero!".

Các kết quả nếu là số thực thì làm tròn đến 2 chữ số thập phân.

Input: gồm 3 thông số:

1-2 : hai số nguyên a và b

3 : mô tả option như nêu trên



In [8]:
def Caculate(a,b,option):
    if option ==1:
        print(a+b)
    elif option==2:
        print(a-b)
    elif option==3:
        print(a*b)
    elif option==4:
        if b==0:
            print("Do not divide 6 by zero!")
        else:
            print(a/b)
    elif option==5:
        print(a**2+b**2)
Caculate(1,3,3)

3


Câu 127: Viết chương trình tìm số lớn nhất trong ba số thực a, b, c nếu giá trị a = b = c thì in ra giá trị đó.

Input: a, b, c
    
Output: Max value = X
    
Example:
    
Input: 5.3 , 7.0, 2.7
    
Output: Max value = 7.000000

In [3]:
a=5.3;b=7.0;c=2.7
Max=a
if b>Max:
    if c>b:
        Max=c
    else:
        Max=b
elif b<Max:
    if c<Max:
        Max=a
    else:
        Max=c
elif Max==a==b==c:
    Max=a
print(Max)

7.0


Câu 128: Viết chương trình hiển thị True nếu ba đối số theo thứ tự không giảm;
mặt khác, nó trả về False.

Ví dụ: thứ tự (1,2, 3) và in_order (1, 2, 2) đều trả về true, trong khi thứ tự (1, 3,2) trả về false.

In [8]:
def inorder(a,b,c):
    if a<b and b<=c:
        return True
    else:
        return False
inorder(1,3,2)

False

Câu 129: Viết chương trình hỗ trợ tính toán hình học.

Cho 3 cạnh của một tam giác có chiều dài lần lượt là A, B và C.
Hãy kiểm tra xem tam giác này có phải là tam giác cân (trả về 1), tam giác vuông (trả về 2), tam giác vuông cân (trả về 3), hay là tam giác đều (trả về 4).
Ngược lại, trả về 0.

Input: gồm 3 thông số:

1 : mô tả các thông số A, B, C cần thiết



In [16]:
from math import sqrt
def checkTriangle(a,b,c):
    if a==b or a==c or b==c:
        return 1
    elif c==sqrt(a**2+b**2) or a==sqrt(b**2+c**2) or b==sqrt(a**2+c**2):
        return 2
    elif (c==sqrt(a**2+b**2) or a==sqrt(b**2+c**2) or b==sqrt(a**2+c**2)) and (a==b or a==c or b==c):
        return 3
    elif a==b==c:
        return 4
    else:
        return 0
checkTriangle(4,5,3)   

2

Câu 130: Viết chương trình hỗ trợ tính cước taxi.

Biết rằng phí dịch vu taxi được tính theo những trường hợp dưới đây :

– với chiều đường đi dưới 10km, giá phải trả là 10 000 VND/km,

– từ cây số thứ 11 đến cây số thứ 30, giá phải trả là 6 000 VND/km,

– kể từ cây số thứ 31, giá phải trả là 4 000 VND/km.

Input: gồm 1 thông số mô tả chiều dài đường đi d

xuất ra màn hình số tiền chính xác đến 2 chữ số sau dấu phẩy.

In [18]:
def Charge(d):
    if d<=10:
        p=10000*d
        print("Cước phí là",p)
    if 11<=d<=30:
        p=10000*10+6000*(d-10)
        print("Cước phí là",p)
    if d>=31:
        p=10000*10+6000*20+4000*(d-30)
        print("Cước phí là",p)
Charge(23)

Cước phí là 178000


Câu 131: Chương trình tính giá trị tuyệt đối của một số nguyên, xuất ra theo định dạng:
        
Input: một số nguyên
    
Output: giá trị tuyệt đối của số đó

Example:
    
Type in your number: -100
    
The absolute value is 100

In [19]:
def Abs(n):
    if n<0:
        print("Giá trị tuyệt đối của n: ",-n)
    else:
        print("Giá trị tuyệt đối của n: ",n)
Abs(-4)

Giá trị tuyệt đối của n:  4


Câu 132: Viết chương trình in ra kết quả của giá trị a gồm có 1 số lẻ, theo các kiểu

Các option:

'C' : số nguyên (làm tròn trên)

'F' : số nguyên (làm tròn dưới)

Các trường hợp khác : làm tròn với giá trị nguyên gần nhất

Input: gồm 2 thông số

1 : số thực a

2 : mô tả option như nêu trên

Output:

'F': Low value of -18.5 is -19.0

'C': Height value of -18.5 is -18.0

Khác: Round value of -18.5 is -19.0


In [10]:
a=-18.5
option=input("Chọn option (C/F): ")
if option=='F':
        print("Low value of"+str(a)+" is"+str(int(a)-1))
elif option=='C':
    print("Low value of"+str(a)+" is"+str(int(a)))
else:
    print("Round of"+str(a)+" is"+str(int(a)-1))

Chọn option (C/F): C
Low value of-18.5 is-18


Câu 133: Viết chương trình chuyển đổi nhiệt độ với các tùy chọn từ người dùng
    
- Nếu người dùng nhâp vào ký tự 'F' thì cho nhập vào nhiệt độ temp và đổi sang nhiệt độ C theo công thức:

C = (5/9)(temp - 32)

- Trường hợp ký tự 'C' thì thì cho nhập vào nhiệt độ temp và đổi sang nhiệt độ F theo công thức:

F = (9/5)temp + 32

- Trường hợp khác thì xuất ra "Tuy chon khong hop le!!!"

In [15]:
option=input("Chọn option (C/F): ")
if option=="C":
    temp=float(input("Nhập vào nhiệt độ(F): "))
    print("Chuyển đổi nhiệt độ sang C: ",5/9*(temp-32))
elif option=='F':
    temp=float(input("Nhập vào nhiệt độ(C): "))
    print("Chuyển đổi nhiệt độ sang F: ",9/5*temp+32)
else:
    print("Tùy chọn không hợp lệ")

Chọn option (C/F): F
Nhập vào nhiệt độ(C): 190
Chuyển đổi nhiệt độ sang F:  374.0


Câu 134: Viết chương trình hiển thị các câu chào với giờ biết trước:

- Nếu từ 5h và nhỏ hơn 12h thì xuất ra "Chao buoi sang"
- Nếu từ 12h và nhỏ hơn 18h thì xuất ra "Chao buoi trua"
- Nếu từ 18h và nhỏ hơn 24h thì xuất ra "Chao buoi toi"
- Nếu từ 24h trở đi thì xuất ra "Troi da khuya"

In [7]:
def checkhours(n):
    hours=float(input("Mấy giờ rồi: "))
    if 5<= hours<=12:
        print("Chào buổi sáng")
    elif 12<=hours<=18:
        print("Chào buổi trưa")
    elif 18<=hours<=24:
        print("Chào buổi tối")
    else:
        print("Trời đã khuya")
checkhours(5)

Mấy giờ rồi: 19
Chào buổi tối


Câu 135: Viết chương trình đưa vào 1 số thể hiện góc phần tư của hệ trục tọa độ, chương trình sẽ hiển thị khoảng góc tương ứng:
- 1 -> "Between 0 and 90 degrees"
- 2 -> "Between 90 and 180 degrees"

...

- Ngược lại -> "Not exists".

Biết rằng độ rộng hiển thị cho các độ là 5 và canh lề trái.

In [10]:
quaters_angle=int(input("Góc phần tư thứ: "))
if quaters_angle==1:
    print("Between 0 and 90 degrees")
elif quaters_angle==2:
    print("Between 90 and 180 degrees")
elif quaters_angle==3:
    print("Between 180 and 270 degrees")
elif quaters_angle==4:
    print("Between 270 and 360 degrees")
else:
    print("Not exists")

Góc phần tư thứ: 5
Not exists


Câu 136: Viết chương trình xuất ra từ "Loop Programming!" 125 lần.

- Không có xuống hàng ở dòng cuối cùng

In [ ]:
for i in range(125):
    print("Loop Programmming")

Câu 137: Hiện thực hàm SumN(int N) tính tổng từ 1 đến N số, N >= 0 .

Xuất kết quả cuối cùng ra màn hình

In [13]:
def SumN(n):
    s=0
    for i in range(1,n+1):
        s+=i
    print("Tổng các số từ 1 đến n là: ",s)
SumN(29)

Tổng các số từ 1 đến n là:  435


Câu 138: Hiện thực hàm OddSum(int N) tính tổng các số lẻ trong đoạn 1 đến N, N >= 0

In [15]:
def OddSum(n):
    s=0
    for i in range(1,n+1):
        if i%2!=0:
            s+=i
    print("Tổng các số lẻ từ 1 đến n là: ",s)
OddSum(19)

Tổng các số lẻ từ 1 đến n là:  100


Câu 139: Viết void enumSum(unsigned int n) liệt kê n số từ 1 đến n, với mỗi số k (1<= k <= n) thực hiện tính tổng từ 1 đến số thứ k đó. Xuất ra màn hình
gồm có 2 cột, mỗi cột cách nhau 1 TAB. Không xuống hàng ở dòng cuối cùng.

Input: số nguyên > 0
Output: Xuất ra kết quả
Example:

Input: n = 4

 n    Sum
--    -
1    1

2    3

3    6

4    10

Total    20

In [18]:
def enumSum(n):
    s=0
    for i in range(1,n+1):
        s+=i
        print(str(i)+"\t"+str(s))
enumSum(5)

1	1
2	3
3	6
4	10
5	15


Câu 140: Hiện thực hàm void MinusInt(int M, int N) tính trong khoảng M, N. Với M, N >= 0.

Nếu M < N thì xuất ra "Input Error!!!"

Ngược lại xuất ra kết quả hiệu các số chẵn trong khoảng đó.

In [23]:
def MinusInt(m,n):
    if m<n:
        print("Input Error!!!")
    else:
        dem=0
        h=0
        for i in range(n,m+1):
            if i%2==0:
                dem+=1
                if dem ==1:
                    h=i
                else:
                    h-=i
        if dem==1:
            print("Hiệu các số chẵn là: ",i)
        elif dem==0:
            print("Not Values")
        else:
            print("Hiệu các số chẵn là: ",h)
MinusInt(9,3)           

Hiệu các số chẵn là:  -10


Câu 141: Viết chương trình đếm và trả về số lượng các ký số trong số nguyên a.

Input: 1 thông số mô tả giá trị a cần nhập

Output: trả về số lượng

Example:

Input: -980

Output: 3


In [12]:
def countDigit(n):
    count=1
    c=abs(n)
    while(c>=10):
        c=c/10
        count+=1
    return count
countDigit(-108)

3

Câu 142: Viết chương trình hiển thị hình tam giác vuông sao có chiều cao là h. Không xuống hàng ở dòng cuối cùng.
Input: giá trị h cần nhập.

Ví dụ: h = 5, thì in ra

*

**

\***

\****

\*****

In [6]:
for i in range(6):
    print(i*"*")


*
**
***
****
*****


Câu 143: Viết chương trình xuất ra màn hình 1 số có là số nguyên tố không, không có xuống hàng.

Example:

Input: 2

Output: 2 is prime

Input: 6

Output: 6 is not prime

In [9]:
def isprime(n):
    dem=0
    for i in range(1,n+1):
        if n%i==0:
            dem+=1
    if dem==2:
        print(n,"is prime")
    else:
        print(n,"is not prime")
isprime(19)

19 is prime


Câu 144: Viết chương trình tìm số nguyên ứng với việc đảo ngược các chữ số trong số nguyên dương a.

Input: 1 thông số mô tả giá trị a cần nhập.

Ví dụ:

*) a = 501 trả về 105

*) a = 1001 trả về 1001

*) a = 2340 trả về 432

In [35]:
def reverveNumber(a):
    reverse=0
    while a>0:
        reverse=reverse*10+a%10
        a=a//10
    return reverse
reverveNumber(1909)

9091

Câu 145: Viết chương trình hiển thị hình tam giác sao có chiều cao là h.

Input: giá trị h cần nhập.

Ví dụ: h = 5, thì in ra

    *
    
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \* *
   
&nbsp;&nbsp;&nbsp;&nbsp;  \* * *
  
&nbsp;&nbsp;&nbsp; \* * * *
 
&nbsp;&nbsp;&nbsp;\* * * * *

In [29]:
def printStar(n):
    for i in range(1,n+1):
        for k in range(1,n-i+1):
            print(" ",end='')
        for k in range(1,i+1):
            print("* ",end='')
        print("\n")
printStar(5)

    * 

   * * 

  * * * 

 * * * * 

* * * * * 



Câu 146: Viết chương trình hiển thị tất cả k chữ cái đầu tiên (in hoa) trong bảng chữ cái tiếng Anh thông qua việc sử dụng 1 vòng lặp.
Định dạng: gồm nhiều dòng, mỗi dòng có tối đa 5 chữ cái cách nhau bởi một khoảng trắng và không có khoảng trắng ở cuối dòng.

Input: giá trị k cần nhập.

Ví dụ: k = 7

A B C D E

F G


In [62]:
def printABC(k):
    for i in range(65,65+k):
        if i-65<4:
            print(chr(i),end=" ")
        else:
            print(chr(i),end='\n')
printABC(9)

A B C D E
F
G
H
I


Câu 147; Viết hàm để in ra tất cả các số nguyên tố trong một phạm vi nhất định (không bao gồm giới hạn trên). Mỗi testcase được mô tả như sau:

Đầu vào: N M
    
0 <= N <= 1000

0 <= M <= 1000

Thí dụ:
    
Đầu vào: 1 10
    
Đầu ra: 2 3 5 7

Đầu vào: 3 5
    
Đầu ra: 3

Đầu vào: 24 28
    
Đầu ra:

In [73]:
def printprime(m,n):
    for i in range(m,n+1):
        dem=0
        for j in range(1,i+1):
            
            if i%j==0:
                dem+=1
        if dem==2:
            print(j,end=' ')
    print("\nĐã kiểm tra")
printprime(24,29)        

29 
Đã kiểm tra


Câu 148: Viết hàm void drawRectangle(int h, int w) để vẽ hình chữ nhật, với chiều cao h, và độ rộng w

Thí dụ:

Input

h = 3, w = 4

\*----*

\*  &nbsp;&nbsp;   *

\*----*

In [92]:
def drawRectangle(h,w):
    for i in range(h):
        print("*")
        for i in range(w):
            print("-",end='')
drawRectangle(3,4)        

*
----*
----*
----

Câu 149: Hãy cài đặt hàm multipleOfNumber thực hiện in ra tất cả các số trong đoạn [M, N] cách nhau bởi khoản trắng ngoại trừ các số là nhân của một giá trị K.

Nếu M lớn hơn N thì xuất ra chuỗi " Need M <= N and K != 0" có xuống hàng.

Tên hàm: multipleOfNumber

Tham số input: Các số nguyên M, N, K

Output: xuất các số

In [9]:
def multipleOfNumber(M,N,K):
    if M<=N and K!=0:
        for i in range(M,N+1):
            if i!=K:
                print(i,end=' ')
    else:
        print("Need M <= N and K != 0")
multipleOfNumber(-3,4,2)

-3 -2 -1 0 1 3 4 

Câu 150: Viết hàm multTable in ra bảng sau

1 2 3

2 4 6

3 6 9

Input: Rows, Cols

Output: các  giá trị cách nha 1 khoản trắng

Lưu ý ko có xuống hàng ở dòng cuố cùng

In [12]:
def multTable(n):
    for i in range(1,n+1):
        print(i,end=' ')
    print("\n")
    for j in range(1,n+1):
        print(2*j,end=' ')
    print("\n")
    for k in range(1,n+1):
        print(3*k,end=' ')
multTable(3)        

1 2 3 

2 4 6 

3 6 9 

Câu 151: Hiện thực hàm xuất các phần tử mảng một chiều nguyên với các phần tử cách nhau khoảng trắng và không có khoảng trắng cuối cùng.

Tên hàm: printArray

Input: Mảng số nguyên, kích thước mảng

Output: Xuất kết quả



In [101]:
def printArray(n):
    for i in n:
        print(i,end=' ')
printArray([1,3,4])

1 3 4 

Câu 152: Hiện thực hàm xuất các phần tử mảng một chiều nguyên gồm 2 cột cách nhau 1 TAB và không có xuống hàng ở dòng cuối cùng.

Tên hàm: printIndexEle

Input: Mảng số nguyên, kích thước mảng

Output: Xuất kết quả

Example:

0      5

1     10

2      0

3      2

4      4

In [14]:
def printIndexEle(A):
    for i in range(len(A)):
        print(i,"\t",A[i])
printIndexEle([1,3,4])

0 	 1
1 	 3
2 	 4


Câu 153: Hiện thực hàm tổng các phần tử mảng một chiều thực xuất ra theo định dạng 2 số thập phân và có xuống hàng ở dòng cuối cùng.

Tên hàm: sumArray

Input: Mảng số thực, kích thước mảng

Output: Xuất kết quả

Example:

Input: -1. 10 2 5 -1

In [106]:
def sumArray(A):
    s=0
    for i in A:
        s+=i
    print("%.2f"%s)
sumArray([2,3,4,5,6])

20.00


Câu 154: Kiểm tra mảng có chứa số chẵn không? Nếu có trả về “1”, ngược lại trả về “0”.

Function:  EvenNumberIncludingArray, 

Input:  Mảng, kích thước mảng

Output: True, False



In [111]:
def EvenNumberIncludingArray(A):
    for i in A:
        if i%2==0:
            return 1
        else:
            return 0
EvenNumberIncludingArray([6,6,8])

1

Câu 155: Kiểm tra mảng có chứa số nguyên tố không? Nếu có trả về “1”, ngược lại trả về “0”

In [20]:
def ngto(n):
    if n<2:
        return True
    else:
        for i in range(2,n):
            if n%i==0:
                return False
    return True
def PrimeNumberIncludingArray(A):
    for i in range(len(A)):
        if ngto(A[i]):
            return True
    return False
PrimeNumberIncludingArray([1,3,4,5])

True

Câu 156: Kiểm tra mảng có chứa giá trị k không? Nếu có trả về “1”, ngược lại trả về “0”.

Function: FindKArray

In [123]:
def FindKArray(A,k):
    for i in range(len(A)):
        if A[i]==k:
            return 1
            break
    return 0
FindKArray([3,4,5],4)

1

Câu 157: Xác định phần tử đầu tiên có giá trị là số nguyên tố và nhỏ hơn 100; và trả về vị trí của phần tử đó, ngược lại trả về -1

In [18]:
def ngto(n):
    if n<=2:
        return False
    else:
        for i in range(2,n):
            if n%i==0:
                return False
    return True
def FindPrimeArray(A):
    for i in range(len(A)):
        if A[i]<100:
            if ngto(A[i]):
                return i
        else: 
            return -1
FindPrimeArray([1,3,5,19])

1

Câu 158: Xác định số lượng phần tử có giá trị lẻ

In [126]:
def Odd_NumArray(A):
    d=0
    for i in range(len(A)):
        if A[i]%2!=0:
            d+=1
    print(d)
Odd_NumArray([3,4,5,7,8])

3


Câu 159: Xác định phần tử đầu tiên có giá trị lớn nhất trong mảng

In [129]:
def Max_Array(A):
    m=0
    for i in A:
        if i>m:
            m=i
    print(m)
Max_Array([3,4,12,9])

12


Câu 160: Xác định phần tử chẵn thứ k trong mảng và trả về giá trị của phần tử đó (trả về “-1” nếu không tồn tại)

In [132]:
B=list()
def Even_Array(A):
    for i in range(len(A)):
        if A[i]%2==0:
            B.append(A[i])
        else:
            B.append(-1)
    print(B)
Even_Array([3,4,5,2])

[-1, 4, -1, 2]


Câu 161: Viết một hàm xuất các phần tử của mảng hai chiều (nxm) ra màn hình không có khoảng trắng hay dấu xuống dòng ở cuối,
giữa các phần tử chỉ có đúng 1 khoảng trắng.

Input: Mảng hai chiều, kích thước hàng, kích thước cột

Output: các phần tử của mảng

In [144]:
def printMatrix(A):
    for i in range(len(A)):
        for j in range(len(A[i])):
            print(A[i][j],end=' ')
        print()
printMatrix([[1,2,3],[3,4,4]])

1 2 3 
3 4 4 


Câu 162: Viết một hàm tính tổng các phần tử trong ma trận (nxm) kiểu số thực và trả về giá trị đó.

int sumMatrix(int M[100][100], int rows, int cols)

Input: Ma trận, kích thước hàng, kích thước cột

Output: Tổng các phần tử

In [150]:
def sumMatrix(A):
    Sum=0
    for i in range(len(A)):
        for j in range(len(A[i])):
            Sum+=A[i][j]
    print(Sum)
sumMatrix([[3,4,3],[9,4,5]])

28


Câu 163: Viết một hàm tính tổng các phần tử nằm phía trên đường chéo chính (bao gồm đường chéo chính) ma trận vuông kích
thước nxn kiểu số thực và trả về giá trị đó.

Input: Ma trận, kích thước

Output: Tổng các phần tử

In [149]:
def trace_matrix(A):
    trace=0
    for i in range(len(A)):
        trace+=A[i][i]
    print(trace)
trace_matrix([[1,3,4],[4,5,6],[3,4,3]])

9


Câu 164: Đếm xem có bao nhiêu phẩn tử chẳn trong matrix

In [152]:
def even_numMatrix(A):
    count=0
    for i in range(len(A)):
        for j in range(len(A[i])):
            if A[i][j]%2==0:
                count+=1
    print(count)
even_numMatrix([[3,4,5],[2,4]])

3


Câu 165: Hiện thực hàm tính tổng các dòng lẻ của matrix

In [22]:
def SumOddRowsMatrix(A):
    Sum=0
    for i in range(1,len(A),2):
        for j in range(len(A[i])):
            Sum+=A[i][j]
    return Sum
SumOddRowsMatrix([[3,4,5],[2,4,3]])

9

Câu 166: Để hiện thực ma trận, người ta dùng một mảng hai chiều. Hãy hiện thực hàm 

void addMatrix(int matrix1[][100], int matrix2[][100], int matrix3[][100], int row, int col)

với các tham số lần lượt là:
- matrix1, matrix2: hai ma trận đầu vào
- matrix3: ma trận kết quả của phép cộng hai ma trận matrix1, matrix2
- row, col: số hàng và cột của hai ma trận.

In [155]:
def add_Matrix(A,B):
    for i in range(len(A)):
        for j in range(len(A[i])):
            A[i][j]=A[i][j]+B[i][j]
    print(A)
add_Matrix([[1,2,3],[2,3,4]],[[4,3,2],[3,2,3]])

[[5, 5, 5], [5, 5, 7]]


In [153]:
[[1,3,4],[3,3,5]]+[[1,3,2],[2,3,4]]

[[1, 3, 4], [3, 3, 5], [1, 3, 2], [2, 3, 4]]

Câu 167: Một ma trận vuông A được gọi là đối xứng nếu ma trận A' = A, với A' là ma trận chuyển vị.

Hiện thực hàm isSymmetricMatrix để kiểm tra xem một ma trận vuông có phải là ma trận đối xứng không?

Nếu đối xứng thì trả về 1, ngược lại trả về 0.

In [23]:
def isSymmetricMatrix(A):
    Sum=0
    for i in range(len(A)):
        for j in range(len(A[i])):
            if A[i][j]==A[j][i]:
                Sum+=1
    if Sum==len(A)*len(A[i]):
        return 1
    else:
        return 0
isSymmetricMatrix([[1,7,3],[7,4,5],[3,5,6]])

1

Câu 168: Một ma trận A được gọi là tam giác dưới (lower triangular) nếu tất cả các phần tử bên trên đường chéo chính là
bằng 0. Hiện thực hàm lowerTriangular trả về true nếu ma trận là tam giác dưới, và false cho ngược lại.

In [29]:
def lower_triangular(A):
    count=0
    for i in range(len(A)):
        count+=1
        for j in range(count,len(A[i])):
            if A[i][j]==0:
                return True
    return False
lower_triangular([[1,0,0],[2,2,0],[3,3,3]])                

True

Câu 169: Kiểm tra một ma trận có phải là ma trận thưa hay không, chúng ta chỉ cần kiểm tra tổng số phần tử bằng không.
Ma trận là ma trận thưa nếu T ≥ ((m * n) / 2); trong đó T xác định tổng số phần tử bằng không. Nếu là ma trận thưa thì
xuất ra chuỗi "Is a Sparse matrix.", ngược lại "Is not Sparse matrix."

In [34]:
def sparsematrix(A):
    count_zero=0
    for i in range(len(A)):
        for j in range(len(A[i])):
            if A[i][j]==0:
                count_zero+=1
    if count_zero>=(len(A)*len(A[i]))//2:
        print("Is a Sparse matrix.")
    else:
        print("Is not Sparse matrix.")
sparsematrix([[0,3,0,0],[2,0,0,0]])

Is a Sparse matrix.


Câu 170: Hiện thực chương trình in dấu hoa thị '*', tại những vị trí mà các phần từ của 2 matrix cùng kích thức (mxn) là bằng nhau, ngược lại thì in khoảng trắng. Không có xuống hàng ở dòng cuối cùng.

Example

A

1 2 3

4 5 6

B

1 3 4

5 5 6

Output

\* - -

\- * -

In [41]:
def printAsterisk(A,B):
    for i in range(len(A)):
        for j in range(len(A[i])):
            if A[i][j]==B[i][j]:
                print('*',end='')
            else:
                print(" ")
A=[[1,3,4],[3,4,2]]
B=[[2,3,4],[9,4,3]]
printAsterisk(A,B)           

 
** 
* 


Câu 171: Hiện thực hàm void assignChar(char outStr[10], char c) để khởi tạo một chuỗi có kích thước là 10 bằng cách gán một ký tự  vào chuỗi các ký .

Input: Chuỗi ký tự, ký tự
    
Output: Chuỗi được gán

In [48]:
def assignChar(string):
    for i in string:
        i = 'F'
        print(i,end='')
assignChar("akme")

FFFF

Câu 172: Một hàm getRooms yêu cầu đầu vào là tên và nếu người dùng có tên bắt đầu bằng chữ cái giữa P và S, với các thông báo sau hiển thị đến người dùng:
- Đặc biệt: "You must go to room 4223 for your key."
- Khác: "You can get your keys here."

Lưu ý: không phân biệt ký tự hoa và thường.


In [50]:
def getRooms(string):
    if string[0]=='P' or string[0]=='S':
        print("You must go to room 4223 for your key.")
    else:
        print("You can get your keys here.")
getRooms("Phon")

You must go to room 4223 for your key.


Câu 173: Hiện thực hàm strLength trả lại chiều dài của chuỗi
    
Input: Chuỗi ký tự
    
Output: chiều dài
    
Example:
    
Input: Hello
    
Output: 5

In [58]:
def stringlen(A):
    count=0
    for i in A:
        count+=1
    return count
stringlen("aame")
     

4

Câu 174: Hiện thực hàm concateString, cộng 2 chuỗi S1, S2 kết quả được lưu trữ vào chuỗi S3. Biết chiều dài S1 cộng chiều dài S2 luôn nhỏ hơn hoặc bằng S3 và chiều dài lớn nhất của chuỗi S3 là 20.

Input: chuỗi đích, chuỗi nguồn 1, chuỗi nguồn 2

Output: Xuất ra màn hình chuỗi đích

In [165]:
s1="Chuỗi 1"
s2="Chuỗi 2"
s3=s1+s2
s3

'Chuỗi 1Chuỗi 2'

Câu 175: Hãy hoàn thành định nghĩa hàm int countCharacter(const char str[], char key) dùng để đếm trong chuỗi str có bao nhiêu ký tự key.

Ví dụ: char = "IOUigc9ZamIo8dOsbf4g58VrEAIGC", key = 'O', hàm trên trả về 2.


In [167]:
def countCharacter(string,key):
    count=0
    for i in range(len(string)):
        if string[i]==key:
            count+=1
    return count
countCharacter("IOamamsamdkwme","a")

3

Câu 176: Hãy viết hàm void StringReverse(char str[]) dùng để đảo thứ tự của một chuỗi ký tự.

Ví dụ: str = "abc", sau khi gọi hàm reverse thì str = "cba".



In [175]:
def StringReverse(string):
    string_new=string[-1::-1]
    return string_new
StringReverse("4aksm")

'mska4'

Câu 177: Hãy hoàn thành định nghĩa hàm void deleteAllCharacter(char str[], char key) dùng để xóa hết các kí tự key xuất hiện trong chuỗi str.

Ví dụ: str = "YZ D6BUc jr ZgwPP s5tpY ElsUi8x cq CS7wCfyOtF YdWP KHJ2H s HpMAI", key = 'c'

thì sau khi gọi hàm trên str = "YZ D6BU jr ZgwPP s5tpY ElsUi8x q CS7wCfyOtF YdWP KHJ2H s HpMAI".

In [73]:
def deleteCharacter(string,key):
    for i in range(len(string)):
        if string[i]==key:
            for j in range(len(string)-1):
                print(string[j+1],end='')
                i-=1
deleteCharacter('signal','i')

ignal

Câu 178: Hãy in ra các từ xuất hiện trong một chuỗi ký tự gồm nhiều từ, ngăn cách nhau bởi một hoặc nhiều khoảng trắng.

Ví dụ: "This is  a   green apple" thì in ra:

This

is

a

green

apple

Lưu ý: Phía đầu và phía cuối của chuỗi không có khoảng trắng. Dòng cuối cùng được in không có dấu xuống dòng ở cuối.



In [184]:
def PrintString(string):
    for i in string.split(" "):
        print(i)
PrintString("This is a green apple")

This
is
a
green
apple


Câu 179: Đếm số ký tự không thuộc bảng chữ cái

In [196]:
def count_alphabet(string):
    count=0
    for i in range(len(string)):
        if not(65<=ord(string[i])<=90 or 97<=ord(string[i])<=122):
            count+=1
    return count
count_nonABC("amam13920")

5

Câu 180: Loại bỏ các khoảng trắng thừa trong chuỗi. Nếu chuỗi chỉ chứa toàn khoản trắng thì gán chuỗi là rỗng (Null).

Example: \_Hello_|_You_
    
Output: Hello You

Function: remSpace

Input: Chuỗi ký tự

In [4]:
def remSpace(string):
    s=string.split(' ')
    for i in s:
        print(i,end='')
remSpace("Sam amd a32")

Samamda32

Câu 181: Chúng ta có thể xác định một cách đệ quy số lượng tổ hợp của m trong số n,
ký hiệu C (n, m), cho n> = 1 và 0 <= m <= n, bằng

C (n, m) = 1 nếu m = 0 hoặc m = n

C (n, m) = C (n-1, m) + C (n-1, m-1) nếu 0 <m <n.

Viết hàm đệ quy recursC để tính C(n,m)


In [78]:
def recursC(n,m):
    if m==1 or m==n :
        return 1
    else:
        return recursC(n-1,m)+ recursC(n-1,m-1)
recursC(5,2)    

4

Câu 182: Palindrome là một chuỗi đọc giống nhau cả về phía trước và phía sau.

Một số ví dụ là “ABCBA” “RADAR” “otto” “I am ma i” “C”

Viết một hàm palindrome bằng cách sử dụng đệ quy để kiểm tra một chuỗi và trả về true nếu nó là palindrome,

ngược lại, trả về false

In [101]:
def palindrome(string):
    for i in range(len(string)):
        if string[i]==string[len(string)-1-i]:
            return True
    return False
palindrome("RADAR")

True

Câu 183: Hãy hiện thực hàm avgArray tính giá trị trung bình của mảng với các tham số sau:

- Tham số thứ nhất là con trỏ số nguyên

- Tham số thứ hai là số phần tử

- Tham số thứ ba là con trỏ số thực kiểu double để trả về giá trị trung bình

Câu 184: Hiện thực hàm intitalArray dùng để cấp phát động N phẩn tử số nguyên và tất cả phần tử được gán bởi một giá trị đầu vào. Cuối cùng hàm trả về địa chỉ của vùng nhớ đó cho người dùng.

Input: N, value

Output: Địa chỉ của vùng nhớ vừa được gán bởi giá trị value



Câu 185: Cho trước một cấu trúc sinh viên gồm: name, gender và height.

Hãy hiện thực hàm XuatStruct để xuất ra danh sách các sinh viên theo định dạng mỗi cột cách nhau một TAB và làm tròn

2 số thập phân cho field height. Biết hàm gồm 2 tham số:

- Một con trỏ cấu trúc sinh viên

- Số lượng sinh viên

In [84]:
Sinhvien={'name':1,'gender':'male','height':190}
for key,value in Sinhvien.items():
    print(key,"\t",value)

name 	 1
gender 	 male
height 	 190


Câu 186: Viết chương trình in ra n số nguyên tố đầu tiên

Câu 187: Viết chương trình nhập số nguyên dương n. Tìm số nguyên dương m lớn nhất
sao cho: 1 + 2 + ... + m < n.

Câu 188: Tìm các bộ (trâu đứng, trâu nằm, trâu già) thỏa mãn bài toán cổ:

Trăm trâu ăn trăm bó cỏ
Trâu đứng ăn năm
Trâu nằm ăn ba
Lụ khụ trâu già
Ba con một bó

Thử tìm cách giảm số vòng lặp khi tính toán xuống.

Câu 189: Với n cho trước, tính tổng S, biết:

Nếu n chẵn: S = 2 + 4 + 6 + ... + n

Nếu n lẻ: S = 1 + 2 + 3 + ... + n

In [87]:
def Odd_Even_Sum(n,option='even'):
    Sum=0
    if option=='even':
        for i in range(2,n+1,2):
            Sum+=i
    else:
        for i in range(1,n+1):
            Sum+=i
    return Sum
Odd_Even_Sum(9)

20

Câu 190: Viết chương trình thực hiện thuật toán sàng Erastosthenes10 (Sieve of
Erastosthenes) để in ra các số nguyên tố nhỏ hơn số n cho trước (n < 100).

Câu 191: Viết chương trình thực hiện những yêu cầu sau:

a. Tạo ngẫu nhiên mảng một chiều n phần tử nguyên có giá trị chứa trong đoạn
[-100, 100] và xuất mảng.

b. Tính tổng các số nguyên dương có trong mảng.

c. Xóa phần tử có chỉ số p (p nhập từ bàn phím) trong mảng.

Câu 192: Viết chương trình thực hiện những yêu cầu sau:
        
a. Tạo ngẫu nhiên mảng một chiều n phần tử nguyên có giá trị chứa trong đoạn
[-100, 100] và xuất mảng.

b. Đếm số phần tử chia hết cho 4 và có chữ số tận cùng là 6.

c. Thay các phần tử lẻ bằng 2 lần giá trị của nó.

Câu 193: Viết chương trình thực hiện những yêu cầu sau:
        
a. Tạo ngẫu nhiên mảng một chiều n phần tử nguyên có giá trị chứa trong đoạn
[-100, 100] và xuất mảng.

b. Dùng một vòng lặp, tìm phần tử có trị nhỏ nhất và lớn nhất của mảng.

c. Xóa các phần tử trong mảng có trị trùng với giá trị lớn nhất của mảng, trừ
phần tử tìm được đầu tiên.

Câu 194: Viết chương trình thực hiện những yêu cầu sau:
        
a. Tạo mảng một chiều n phần tử nguyên có giá trị nhập vào từ bàn phím.

b. Kiểm tra xem mảng có đối xứng hay không.

c. Hãy dịch trái xoay vòng mảng k lần, k nhập từ bàn phím.

In [99]:
def checkArray(A):
    for i in range(len(A)):
        if A[i]==A[len(A)-1-i]:
            return True
    return False
checkArray([1,3,5])

True

Câu 195: Viết chương trình thực hiện những yêu cầu sau:
        
a. Tạo mảng một chiều n phần tử nguyên có giá trị nhập vào từ bàn phím.

b. In ra các phần tử trong mảng có trị phân biệt.

Câu 196: Viết chương trình thực hiện những yêu cầu sau:

a. Tạo mảng một chiều n phần tử nguyên có giá trị nhập vào từ bàn phím.

b. Tìm các phần tử có số lần xuất hiện là như nhau và nhiều nhất.

Câu 197: Viết chương trình thực hiện những yêu cầu sau:
        
a. Tạo ngẫu nhiên mảng một chiều n phần tử nguyên có giá trị chứa trong đoạn
[-100, 100] và xuất mảng.

b. Tính tổng nghịch đảo các phần tử trong mảng.

c. Viết hàm duyệt các phần tử A[i] của mảng theo thứ tự từ trái sang phải; nếu
A[i] lẻ thì xóa một phần tử bên phải nó.

Câu 198: Viết chương trình thực hiện những yêu cầu sau:
        
a. Tạo ma trận có kích thước n x m (n, m nhập từ bàn phím) với các phần tử là
các trị ngẫu nhiên trong đoạn [-100, 100], xuất ma trận.

b. Chuyển ma trận A thành ma trận chuyển vị A* và in ra.

Câu 199: Tạo ma trận vuông bậc 5 với các phần tử có trị từ 1, 2, ..., 25, sắp xếp giảm
theo hình zigzag từ trái sang phải, từ trên xuống dưới.

Câu 200: Viết chương trình yêu cầu nhập vào chuỗi ký tự có chiều dài tối đa là 80
ký tự. Nhập vào hai số nguyên dương n và p, trong chuỗi trên tiến hành xóa n ký tự
bắt đầu từ vị trí p.